name: event_extreme   # change the name here 
dependencies:           # include all the packages you need in the project
    - python>=3.10
    - pytest
    - sphinx
    - pip
    - matplotlib
    - pandas
    - numpy
    - scipy
    - pip:              # include the packages that can only be installed by pip
        - myst_parser
        - nbsphinx
        - mdutils
